

-- order distribute
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (17, -3, '订单配货', 'OrderDistribute','/order-distribute', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.domain.AreaAddress' where admin_section_id=17;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (17,79);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (17,80);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (17,81);

-- order delivery
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (18, -3, '订单发货', 'OrderDelivery', '/order-delivery', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.domain.Dormitory' where admin_section_id=18;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (18,79);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (18,80);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (18,81);

-- order complete
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (19, -3, '订单完成', 'OrderComplete', '/order-complete', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.domain.MyAddress' where admin_section_id=19;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (19,79);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (19,80);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (19,81);

-- inventory
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (20, -1, '库存警告', 'SsbInventory', '/xiao-inventory', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.region.domain.Region' where admin_section_id=20;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (20,77);

//invoicing
insert into blc_admin_permission values(83,'invoicing','permission_all','READ');
insert into blc_admin_permission values(82,'invoicing','permission_all','CREATE');


INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (247, 'com.ssbusy.core.invoicing.domain.Invoicing', 82);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (248, 'com.ssbusy.core.invoicing.domain.Invoicing', 83);


insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 82);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 83);

INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (21, -1, '进销存', '进销存', '/Invoicing', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.invoicing.domain.Invoicing' where admin_section_id=21;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (21,82);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (21,83);

//统计信息
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (22, -2, '统计信息', '统计信息','/statistics', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.domain.AreaAddress' where admin_section_id=22;
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (22,79);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (22,80);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (22,81);

//停车场

INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (85,'Update Carbarn','PERMISSION_UPDATE_CARBARN', 'UPDATE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (86,'create Carbarn','PERMISSION_READ_CARBARN', 'CREATE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (87,'delete Carbarn','PERMISSION_ALL_CARBARN','DELETE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (88,'Read Carbarn','PERMISSION_READ_CARBARN', 'READ');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (89,'All Carbarn','PERMISSION_ALL_CARBARN','ALL');

INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (250, 'com.ssbusy.core.carbarn.domain.Carbarn', 85);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (251, 'com.ssbusy.core.carbarn.domain.Carbarn', 86);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (252, 'com.ssbusy.core.carbarn.domain.Carbarn', 87);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (253, 'com.ssbusy.core.carbarn.domain.Carbarn', 88);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (254, 'com.ssbusy.core.carbarn.domain.Carbarn', 89);

insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 85);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 86);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 87);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 88);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 89);

-- tell the admin it needs to load this section also and associate permissions
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (23, -1, 'carbarn', '停车场', '/carbarn', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.carbarn.domain.Carbarn' where admin_section_id=23;

INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,85);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,86);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,87);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,88);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,89);

//入口
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (90,'Update CarEntrance','PERMISSION_UPDATE_CARENTRANCE', 'UPDATE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (91,'create CarEntrance','PERMISSION_READ_CARENTRANCE', 'CREATE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (92,'delete CarEntrance','PERMISSION_ALL_CARENTRANCE','DELETE');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (93,'Read CarEntrance','PERMISSION_READ_CARENTRANCE', 'READ');
INSERT INTO BLC_ADMIN_PERMISSION (ADMIN_PERMISSION_ID, DESCRIPTION, NAME, PERMISSION_TYPE) VALUES (94,'All CarEntrance','PERMISSION_ALL_CARENTRANCE','ALL');

INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (255, 'com.ssbusy.core.carbarn.domain.CarEntrance', 90);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (256, 'com.ssbusy.core.carbarn.domain.CarEntrance', 91);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (257, 'com.ssbusy.core.carbarn.domain.CarEntrance', 92);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (258, 'com.ssbusy.core.carbarn.domain.CarEntrance', 93);
INSERT INTO BLC_ADMIN_PERMISSION_ENTITY (ADMIN_PERMISSION_ENTITY_ID, CEILING_ENTITY, ADMIN_PERMISSION_ID) VALUES (259, 'com.ssbusy.core.carbarn.domain.CarEntrance', 94);

insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 90);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 91);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 92);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 93);
insert into BLC_ADMIN_ROLE_PERMISSION_XREF (ADMIN_ROLE_ID, ADMIN_PERMISSION_ID) values(-1, 94);

-- tell the admin it needs to load this section also and associate permissions
INSERT INTO BLC_ADMIN_SECTION (ADMIN_SECTION_ID, ADMIN_MODULE_ID, NAME, SECTION_KEY, URL, USE_DEFAULT_HANDLER) VALUES (23, -1, 'carbarn', '停车场', '/carbarn', false);
update  blc_admin_section set CEILING_ENTITY='com.ssbusy.core.carbarn.domain.Carbarn' where admin_section_id=23;

INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,85);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,86);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,87);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,88);
INSERT INTO blc_admin_sec_perm_xref (ADMIN_SECTION_ID, ADMIN_PERMISSION_ID) VALUES (23,89);