drop table ssb_invoicing;
CREATE TABLE `ssb_invoicing` (
  `INVOICING_ID` bigint(20) NOT NULL,
  `PURCHASE_DATE` datetime default NULL,
  `PURCHASE_PRICE` decimal(19,5) NOT NULL,
  `PURCHASE_QUANTITY` int(11) NOT NULL,
  `INVENTORY_ID` bigint(20) NOT NULL,
  `RETAIL_PRICE` decimal(19,2) default NULL,
  `SALE_PRICE` decimal(19,2) default NULL,
  PRIMARY KEY  (`INVOICING_ID`),
  KEY `FK1BB5226D9DFA185F` (`INVENTORY_ID`),
  CONSTRAINT `FK1BB5226D9DFA185F` FOREIGN KEY (`INVENTORY_ID`) REFERENCES `blc_inventory` (`INVENTORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;